services:
  hermes-no:
    build: .
    network_mode: bridge
    image: hermes-no
    working_dir: /app
    hostname: "0.0.0.0"
    ports: ["3001:3001"]
    env_file: [.env.local]
    command: node server.js
    restart: unless-stopped
