on:
  push:
    branches: [main]
  workflow_dispatch:
name: 🚀 Deploy
jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🧱 Restart
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.URL}}
          username: ${{secrets.USER}}
          key: ${{secrets.KEY}}
          script: |
            cd ~/narrativeodyssey.uk/hermes-no
            docker compose down
            git fetch origin
            git reset --hard origin/main
            cp ../.env.local .
            screen -S build -d -m bash -c 'docker compose up --build -d'
