on:
  push:
    branches: [main]
  workflow_dispatch:
name: 🚀 Deploy
jobs:
  web-deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🛑 Stop pm2
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.URL }}
          user: ${{ secrets.USER }}
          private_key: ${{ secrets.KEY }}
          command: |
            cd ../home/jlorelai/narrativeodyssey.uk;
            pm2 stop main.config.js;

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: ${{ secrets.URL }}
          remote-user: ${{ secrets.USER }}
          private-ssh-key: ${{ secrets.KEY }}
          destination-path: ../home/jlorelai/narrativeodyssey.uk/hermes

      - name: 🟢 Start pm2
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.URL }}
          user: ${{ secrets.USER }}
          private_key: ${{ secrets.KEY }}
          command: |
            cd ../home/jlorelai/narrativeodyssey.uk;
            chown --recursive root hermes;
            pm2 start main.config.js;
